version: "3" 

services: 
  # zookeeper
  zookeeper: 
    image: 'wurstmeister/zookeeper:latest' 
    ports: 
      - '2181:2181' 
    environment: 
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes: 
      - ../volumes/zookeeper:/var/lib/zookeeper/data
  # kafka
  kafka: 
    image: 'wurstmeister/kafka:latest' 
    ports: 
      - '9092:9092' 
    environment: 
      - KAFKA_BROKER_ID=1 
      - KAFKA_LISTENERS=PLAINTEXT://:9092 
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092 
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=send-mail-topic:1:1,send-sms-topic:1:1,file-certificated-topic:1:1,file-certificated-topic-dlq:1:1,bb.topic.dev.dl.certification:1:1,bb.topic.dev.certification:1,1
    volumes:
      - ../volumes/kafka:/var/lib/kafka/data
    depends_on: 
      - zookeeper